---
# tasks file for aspnet
 - name: Update apt cache
   apt: update_cache=yes cache_valid_time=3600

 - name: Download .Net key
   get_url: 
        url: https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

 - name: Install a .deb package
   apt:
    deb: /tmp/packages-microsoft-prod.deb

 - name: Installing .Net core
   apt:
     update_cache: yes 
     name: dotnet-sdk-2.1 
     state: present

 - name: Copy service file
   copy: src=aspnet.service dest=/etc/systemd/system/
